name: Post on Social
on:
  schedule:
    - cron: "0 17 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Take screenshot and tweet
      run: |
        chmod +x ./index.js
        ./index.js
