name: Post on Social
on:
  schedule:
    - cron: "0 17,23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Take screenshot and tweet
      env: 
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
      run: |
        chmod +x ./index.js
        node ./index.js
